#!/bin/sh
if ! head -1 "$1" | grep -qE "^(Create|Update|Remove|Setup|Revert)(\(.+?\))? .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid. Please follow commit pattern" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,120}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi
